# coding: utf-8

"""
    Karbon Platform Services API reference.

    OpenAPI documentation for public facing Karbon Platform Services API  This API documentation is generated from source code using go-swagger. Do not edit the generated kps_api.json directly!  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: karbon-platform-services-api@nutanix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from kps_api.models.kiali_metric import KialiMetric  # noqa: F401,E501


class KialiMetrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'histograms': 'dict(str, dict(str, KialiMetric))',
        'metrics': 'dict(str, KialiMetric)'
    }

    attribute_map = {
        'histograms': 'histograms',
        'metrics': 'metrics'
    }

    def __init__(self, histograms=None, metrics=None):  # noqa: E501
        """KialiMetrics - a model defined in Swagger"""  # noqa: E501
        self._histograms = None
        self._metrics = None
        self.discriminator = None
        if histograms is not None:
            self.histograms = histograms
        if metrics is not None:
            self.metrics = metrics

    @property
    def histograms(self):
        """Gets the histograms of this KialiMetrics.  # noqa: E501


        :return: The histograms of this KialiMetrics.  # noqa: E501
        :rtype: dict(str, dict(str, KialiMetric))
        """
        return self._histograms

    @histograms.setter
    def histograms(self, histograms):
        """Sets the histograms of this KialiMetrics.


        :param histograms: The histograms of this KialiMetrics.  # noqa: E501
        :type: dict(str, dict(str, KialiMetric))
        """

        self._histograms = histograms

    @property
    def metrics(self):
        """Gets the metrics of this KialiMetrics.  # noqa: E501


        :return: The metrics of this KialiMetrics.  # noqa: E501
        :rtype: dict(str, KialiMetric)
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this KialiMetrics.


        :param metrics: The metrics of this KialiMetrics.  # noqa: E501
        :type: dict(str, KialiMetric)
        """

        self._metrics = metrics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KialiMetrics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KialiMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
