
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-09T05:41:48-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ecc25d51c1f902d6cbad2bec3b3c33c4c6ac934",
 "version": "4.7.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
