[tool.poetry]
name = "usb-plug-notification"
version = "0.1.0"
description = "USB plug notification package"
authors = ["Dick Marinus <dick@mrns.nl>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
