[tool.poetry]
name = "test-poetry-publish"
version = "0.1.0"
description = ""
authors = ["Nikia <barinov.nikita49@gmail.com>"]

packages = [
    { include="test-poetry-publish", from="." },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
