[tool.poetry]
name = "discorddefs"
version = "0.1.0"
description = ""
authors = ["AstroOrbis <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "^1.7.3"
wheel = "^0.36.2"
twine = "^3.4.1"
discord-webhook = "^0.14.0"
discord = "^1.7.3"
build = "^0.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12", "setuptools>=54", "wheel"]
build-backend = "poetry.masonry.api"