---
version: 2.1

jobs:
  install:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - setup-py-\{\{ checksum "setup.py" \}\}
      - run:
          name: "Install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[dist,lint,test,types]
      - save_cache:
          paths:
            - ./venv
          key: setup-py-\{\{ checksum "setup.py" \}\}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  lint:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.9.6
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Run flake8"
          command: |
            . venv/bin/activate
            flake8 {{ project }}

  test:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.9.6
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Run pytest"
          command: |
            . venv/bin/activate
            pytest {{ project }}

  types:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.9.6
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Run mypy"
          command: |
            . venv/bin/activate
            mypy {{ project }}

  release:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.9.6
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create distributions
          command: |
            . venv/bin/activate
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - types:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
            - lint
            - types
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
