[tool.poetry]
name = "NeogiInstruments"
version = "2.0.1"
description = "Communication and helper functions for lab equipment"
authors = ["UNT Neogi Lab <BrianSquires@my.unt.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
pyserial = "^3.5"
PyVISA-py = "^0.5.2"
nidaqmx = "^0.5.7"
matplotlib = "^3.4.2"
plotly = "^5.0.0"
param = "^1.10.1"
PyMeasure = "^0.9.0"
pandas = "^1.3.0"
scipy = "^1.7.0"
tabulate = "^0.8.9"
panel = "^0.11.3"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
