name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - cftime
  - dask
  - pip
  - cartopy #installing this without conda is a nightmare, so ill leave it here
  - xesmf # same here
  - pip:
    - codecov
    - pytest-cov
    - pytest-xdist
    - git+https://github.com/mathause/regionmask.git
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/xgcm/xgcm.git
    - git+https://github.com/jbusecke/xarrayutils.git
