# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['blackdogosint',
 'blackdogosint.osint',
 'blackdogosint.osint.term',
 'blackdogosint.osint.utils',
 'blackdogosint.osintlib',
 'blackdogosint.osintlib.Archives',
 'blackdogosint.osintlib.Business_Records',
 'blackdogosint.osintlib.Classifieds',
 'blackdogosint.osintlib.Dark_Web',
 'blackdogosint.osintlib.Dating',
 'blackdogosint.osintlib.Digital_Currency',
 'blackdogosint.osintlib.Documentation',
 'blackdogosint.osintlib.Domain_Name',
 'blackdogosint.osintlib.Email_Address',
 'blackdogosint.osintlib.Encoding_Decoding',
 'blackdogosint.osintlib.Exploits_e_Advisories',
 'blackdogosint.osintlib.Forum_Blog_IRC',
 'blackdogosint.osintlib.Geolocation_Tool_Maps',
 'blackdogosint.osintlib.IP_Address',
 'blackdogosint.osintlib.IP_Address.Geolocation',
 'blackdogosint.osintlib.IP_Address.Geolocation.My_IP_Address',
 'blackdogosint.osintlib.Image_Video_Docs',
 'blackdogosint.osintlib.Instant_Messaging',
 'blackdogosint.osintlib.Language_Translation',
 'blackdogosint.osintlib.Malicious_File_Analysis',
 'blackdogosint.osintlib.Metadata',
 'blackdogosint.osintlib.Mobile_Emulation',
 'blackdogosint.osintlib.OpSec',
 'blackdogosint.osintlib.People_Search_Engines',
 'blackdogosint.osintlib.Public_Records',
 'blackdogosint.osintlib.ScreenShot',
 'blackdogosint.osintlib.Search',
 'blackdogosint.osintlib.Search.google',
 'blackdogosint.osintlib.Search_Engines',
 'blackdogosint.osintlib.Social_Networks',
 'blackdogosint.osintlib.Telephone_Numbers',
 'blackdogosint.osintlib.Terrorism',
 'blackdogosint.osintlib.Threat_Intelligence',
 'blackdogosint.osintlib.Tools',
 'blackdogosint.osintlib.Trainings',
 'blackdogosint.osintlib.Transportation',
 'blackdogosint.osintlib.Username',
 'blackdogosint.osintlib.Username.Specific_Sites',
 'blackdogosint.osintlib.Username.Username_Search_Engines',
 'blackdogosint.resources']

package_data = \
{'': ['*']}

install_requires = \
['Django>=3.2.4,<4.0.0',
 'Pillow>=8.2.0,<9.0.0',
 'PySocks>=1.7.1,<2.0.0',
 'colored-traceback>=0.3.0,<0.4.0',
 'google>=3.0.0,<4.0.0',
 'import-linter>=1.2.1,<2.0.0',
 'importanize>=0.7.0,<0.8.0',
 'isort[requirements_deprecated_finder,pipfile_deprecated_finder]>=5.9.1,<6.0.0',
 'mkdocs-bootswatch>=1.1,<2.0',
 'mkdocs-material>=7.1.9,<8.0.0',
 'mkdocs>=1.2.1,<2.0.0',
 'osint>=0.5,<0.6',
 'pyright>=0.0.2,<0.0.3',
 'pytype>=2021.6.17,<2022.0.0',
 'requests>=2.25.1,<3.0.0',
 'search-engine-parser>=0.6.2,<0.7.0',
 'selenium>=3.141.0,<4.0.0',
 'six>=1.16.0,<2.0.0',
 'socks>=0,<1',
 'standalone>=1.0.1,<2.0.0',
 'toml>=0.10.2,<0.11.0',
 'types-freezegun>=0.1.4,<0.2.0',
 'types-orjson>=0.1.1,<0.2.0',
 'types-pathlib2>=0.1.6,<0.2.0',
 'types-pynamodb>=0.1,<0.2',
 'types-pytz>=2021.1.0,<2022.0.0',
 'types-six>=0.1.7,<0.2.0',
 'types-tabulate>=0.1.1,<0.2.0']

setup_kwargs = {
    'name': 'blackdogosint',
    'version': '0.1.32',
    'description': 'api supporting OSINT open source queries',
    'long_description': None,
    'author': 'darkcode357',
    'author_email': 'darkcode357@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.7,<3.10',
}


setup(**setup_kwargs)
