#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['dunamai']

extras_require = \
{':python_version < "3.8"': ['importlib_metadata'],
 'test': ['pytest', 'pytest-cov', 'pytest-black', 'pygments']}

setup(name='get_version',
      version='3.3',
      description='A version helper in the spirit of versioneer.',
      author='Philipp Angerer',
      author_email='phil.angerer@gmail.com',
      url='https://github.com/flying-sheep/get_version',
      py_modules=['get_version'],
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
