[build-system]
requires = ["setuptools >=42", "wheel", "setuptools_scm[toml] >=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
profile = 'black'
line_length = 80

[tool.pytest.ini_options]
python_files = ['test_*.py']
testpaths = ['tests']

[tool.coverage.run]
branch = true
source = ['webdomains']

[tool.coverage.report]
exclude_lines = ['# pragma: no cover', 'raise NotImplementedError']
show_missing = true
