# coding: utf-8

"""
    Karbon Platform Services API reference.

    OpenAPI documentation for public facing Karbon Platform Services API  This API documentation is generated from source code using go-swagger. Do not edit the generated kps_api.json directly!  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: karbon-platform-services-api@nutanix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kps_api
from models.fields_v1 import FieldsV1  # noqa: E501
from kps_api.rest import ApiException


class TestFieldsV1(unittest.TestCase):
    """FieldsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldsV1(self):
        """Test FieldsV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kps_api.models.fields_v1.FieldsV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
