# coding: utf-8

"""
    Karbon Platform Services API reference.

    OpenAPI documentation for public facing Karbon Platform Services API  This API documentation is generated from source code using go-swagger. Do not edit the generated kps_api.json directly!  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: karbon-platform-services-api@nutanix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kps_api
from api.helm_api import HelmApi  # noqa: E501
from kps_api.rest import ApiException


class TestHelmApi(unittest.TestCase):
    """HelmApi unit test stubs"""

    def setUp(self):
        self.api = api.helm_api.HelmApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_helm_application_create(self):
        """Test case for helm_application_create

        Create Helm Application.  # noqa: E501
        """
        pass

    def test_helm_application_update(self):
        """Test case for helm_application_update

        Update Helm Application.  # noqa: E501
        """
        pass

    def test_helm_template(self):
        """Test case for helm_template

        Run Helm Template.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
