# coding: utf-8

"""
    Karbon Platform Services API reference.

    OpenAPI documentation for public facing Karbon Platform Services API  This API documentation is generated from source code using go-swagger. Do not edit the generated kps_api.json directly!  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: karbon-platform-services-api@nutanix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kps_api
from api.connector_instance_api import ConnectorInstanceApi  # noqa: E501
from kps_api.rest import ApiException


class TestConnectorInstanceApi(unittest.TestCase):
    """ConnectorInstanceApi unit test stubs"""

    def setUp(self):
        self.api = api.connector_instance_api.ConnectorInstanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connector_instance_create(self):
        """Test case for connector_instance_create

        Create a connector instance.  # noqa: E501
        """
        pass

    def test_connector_instance_delete(self):
        """Test case for connector_instance_delete

        Delete a specific connector instance.  # noqa: E501
        """
        pass

    def test_connector_instance_get(self):
        """Test case for connector_instance_get

        Get a connector instance by ID.  # noqa: E501
        """
        pass

    def test_connector_instance_update(self):
        """Test case for connector_instance_update

        Update a connector instance.  # noqa: E501
        """
        pass

    def test_connector_instances_list(self):
        """Test case for connector_instances_list

        Get all connector instances.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
