
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-12T11:31:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4836fc3e5b1335b484eb2bfe2483641959e5d0ea",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
