[tool.poetry]
name = "autoklik"
version = "0.1.1"
description = "Auto clicker built around xdotool."
authors = ["Magnus Walbeck <mw@mwalbeck.org>"]
readme = "README.md"
repository = "https://git.walbeck.it/mwalbeck/autoklik"
packages = [{ include = "autoklik" }]

[tool.poetry.scripts]
autoklik = "autoklik.__init__:main"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.6b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
