
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-09T00:53:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "93b6791f9ea1e8be4a123a7e54f8c56c6278c24d",
 "version": "0.19.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
