# coding: utf-8

"""
    Karbon Platform Services API reference.

    OpenAPI documentation for public facing Karbon Platform Services API  This API documentation is generated from source code using go-swagger. Do not edit the generated kps_api.json directly!  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: karbon-platform-services-api@nutanix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ContainerRegistryInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'pwd': 'str',
        'user_name': 'str'
    }

    attribute_map = {
        'email': 'email',
        'pwd': 'pwd',
        'user_name': 'userName'
    }

    def __init__(self, email=None, pwd=None, user_name=None):  # noqa: E501
        """ContainerRegistryInfo - a model defined in Swagger"""  # noqa: E501
        self._email = None
        self._pwd = None
        self._user_name = None
        self.discriminator = None
        self.email = email
        self.pwd = pwd
        self.user_name = user_name

    @property
    def email(self):
        """Gets the email of this ContainerRegistryInfo.  # noqa: E501

        Email address for the container registry profile user.  # noqa: E501

        :return: The email of this ContainerRegistryInfo.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ContainerRegistryInfo.

        Email address for the container registry profile user.  # noqa: E501

        :param email: The email of this ContainerRegistryInfo.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def pwd(self):
        """Gets the pwd of this ContainerRegistryInfo.  # noqa: E501

        Password for the container registry profile.  # noqa: E501

        :return: The pwd of this ContainerRegistryInfo.  # noqa: E501
        :rtype: str
        """
        return self._pwd

    @pwd.setter
    def pwd(self, pwd):
        """Sets the pwd of this ContainerRegistryInfo.

        Password for the container registry profile.  # noqa: E501

        :param pwd: The pwd of this ContainerRegistryInfo.  # noqa: E501
        :type: str
        """
        if pwd is None:
            raise ValueError("Invalid value for `pwd`, must not be `None`")  # noqa: E501

        self._pwd = pwd

    @property
    def user_name(self):
        """Gets the user_name of this ContainerRegistryInfo.  # noqa: E501

        User name for the container registry profile.  # noqa: E501

        :return: The user_name of this ContainerRegistryInfo.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this ContainerRegistryInfo.

        User name for the container registry profile.  # noqa: E501

        :param user_name: The user_name of this ContainerRegistryInfo.  # noqa: E501
        :type: str
        """
        if user_name is None:
            raise ValueError("Invalid value for `user_name`, must not be `None`")  # noqa: E501

        self._user_name = user_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContainerRegistryInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContainerRegistryInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
