[tool.poetry]
name = "usb-plug-notification-darwin"
version = "0.1.1"
description = "Python script to get plug/unplug events on Darwin (MacOS)"
authors = ["Dick Marinus <dick@mrns.nl>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
pyobjc-framework-Cocoa = "^7.3"
click = "^8.0.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
usb-plug-notification = "usb_plug_notification_darwin.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

