[tool.flit.scripts]
tutturu = "tutturu:main"

[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "tutturu"
author = "Denis Aseev"
author-email = "brerfox33@gmail.com"
classifiers = [ "License :: OSI Approved :: MIT License",]

