#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

entry_points = \
{'console_scripts': ['tutturu = tutturu:main']}

setup(name='tutturu',
      version='0.4.2',
      description='Simple test. Tut-turu))',
      author='Denis Aseev',
      author_email='brerfox33@gmail.com',
      url=None,
      py_modules=['tutturu'],
      entry_points=entry_points,
     )
