
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-06T12:31:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b4e98c1246ef51709a063ed6ccef076c02ea3d5",
 "version": "0.7.0.post.dev246"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
