name: 'mimtitles'

file_metadata:
  description: 'OMIM mim Titles'

source: 'omim'

skip_lines: 2

delimiter: '\t'

files:
  - './examples/data/mimtitles.txt'

columns:
  - 'Prefix'
  - 'MIM Number'
  - 'Preferred Title; symbol'
  - 'Alternative Title(s); symbol(s)'
  - 'Included Title(s); symbols'

key: 'MIM Number'

values:
  - 'type'
  - 'obsoleted'
  - 'replaced by'
