
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-09T11:56:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd562f5f653f5b99c1d8d92e889712bbf2ebc6f3",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
