forward_buffer_size: 1000
feature_index_prefix_bit: 12
slot_config:
  feature1:
    dim: 64
    embedding_summation: true
    sample_fixed_size: 30
  feature2:
    dim: 64
    embedding_summation: false
    sample_fixed_size: 30 
  feature3:
    dim: 64
    embedding_summation: true
    sample_fixed_size: 30
    hash_stack_config:
      hash_stack_rounds: 2
      embedding_size: 4000000
feature_groups: {}
target_config:
  - name: unused
    negative: [unused]
    positive: [unused]