[tool.poetry]
name = "mnemo"
version = "0.0.2"
description = "Notebook and assistant."
authors = ["Gabriele Girelli <gigi.ga90@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ggirelli/mnemo-assistant"
repository = "https://github.com/ggirelli/mnemo-assistant"
keywords = ["assistant", "notebook", "journal", "database"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Science/Research",
    "Operating System :: Unix",
    "Operating System :: POSIX :: Linux",
    "Topic :: Database",
    "Topic :: Database :: Front-Ends",
    "Topic :: Office/Business",
    "Topic :: Office/Business :: News/Diary",
    "Topic :: Office/Business :: Scheduling",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Utilities",
    "Typing :: Typed",
]
include = ["CHANGELOG.md", "LICENSE"]

[tool.poetry.dependencies]
python = "^3.8"
bottle = "^0.12.19"
click = "^8.0.1"
passlib = "^1.7.4"
paste = "^3.5.0"
rich = "^10.4.0"
tinydb = "^4.5.0"

[tool.poetry.scripts]
"mnemo" = "mnemo.scripts.assistant:__main"
"mnemo-autocomplete" = "mnemo.scripts.autocomplete:__main"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
pytest = "^6.2.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
