[tool.poetry]
name = "pyflowcl"
version = "1.0.5"
description = "Cliente para comunicacion con flowAPI-3 de flow.cl"
authors = ["Mario Hernandez <yo@mariofix.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://pyflowcl.readthedocs.io/es/latest/index.html"
repository = "https://github.com/mariofix/pyflowcl"
classifiers=[
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-pep8 = "*"
black = "*"
tox = "*"
thankyou = "^0.0.1"
sphinx = "*"
sphinx-theme = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
