
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-11T06:45:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c20fc02e6462c7bcd8ff6a89d52cf0a05b44047c",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
