"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import proto_profiler
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___DataLocation = DataLocation

class _DataLocation(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataLocation.V],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    CPU = DataLocation.V(0)
    GPU = DataLocation.V(1)
    CPU_NDARRAY = DataLocation.V(2)
    GPU_NDARRAY = DataLocation.V(3)
    MESSAGE = DataLocation.V(4)

class DataLocation(metaclass=_DataLocation):
    V = typing.NewType("V", builtins.int)

CPU = DataLocation.V(0)
GPU = DataLocation.V(1)
CPU_NDARRAY = DataLocation.V(2)
GPU_NDARRAY = DataLocation.V(3)
MESSAGE = DataLocation.V(4)

class TopicMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TOPIC_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    topic: typing.Text = ...
    source: typing.Text = ...
    timestamp: builtins.int = ...
    data: builtins.bytes = ...
    @property
    def trace(self) -> proto_profiler.Trace: ...
    def __init__(
        self,
        *,
        topic: typing.Text = ...,
        source: typing.Text = ...,
        timestamp: builtins.int = ...,
        trace: typing.Optional[proto_profiler.Trace] = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["trace", b"trace"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "data",
            b"data",
            "source",
            b"source",
            "timestamp",
            b"timestamp",
            "topic",
            b"topic",
            "trace",
            b"trace",
        ],
    ) -> None: ...

global___TopicMessage = TopicMessage
