
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-12T20:37:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6367c66b0f1a1b33b35ca0fa068037ab914d7e8",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
