
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-12T06:06:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "26ba6b4846bd4f5edac0f0e63882dfbbe7727f7f",
 "version": "1.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
