[tool.poetry]
name = "sampleproject-merinhunter"
version = "0.1.0"
description = "A sample Python project"
license = "MIT"
authors = ["A. Random Developer <author@example.com>"]
readme = "README.md"
homepage = "https://github.com/pypa/sampleproject"
repository = "https://github.com/pypa/sampleproject"
packages = [
    { include = "sample", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
