# coding: utf-8

"""
    Karbon Platform Services API reference.

    OpenAPI documentation for public facing Karbon Platform Services API  This API documentation is generated from source code using go-swagger. Do not edit the generated kps_api.json directly!  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: karbon-platform-services-api@nutanix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from kps_api.models.entity_version_metadata import EntityVersionMetadata  # noqa: F401,E501


class EdgeInventoryDeltaPayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'applications': 'list[EntityVersionMetadata]',
        'categories': 'list[EntityVersionMetadata]',
        'cloud_profiles': 'list[EntityVersionMetadata]',
        'container_registries': 'list[EntityVersionMetadata]',
        'data_pipelines': 'list[EntityVersionMetadata]',
        'data_sources': 'list[EntityVersionMetadata]',
        'functions': 'list[EntityVersionMetadata]',
        'log_collectors': 'list[EntityVersionMetadata]',
        'ml_models': 'list[EntityVersionMetadata]',
        'project_services': 'list[EntityVersionMetadata]',
        'projects': 'list[EntityVersionMetadata]',
        'runtime_environments': 'list[EntityVersionMetadata]',
        'software_updates': 'list[EntityVersionMetadata]',
        'svc_bindings': 'list[EntityVersionMetadata]',
        'svc_instances': 'list[EntityVersionMetadata]'
    }

    attribute_map = {
        'applications': 'Applications',
        'categories': 'Categories',
        'cloud_profiles': 'CloudProfiles',
        'container_registries': 'ContainerRegistries',
        'data_pipelines': 'DataPipelines',
        'data_sources': 'DataSources',
        'functions': 'Functions',
        'log_collectors': 'LogCollectors',
        'ml_models': 'MLModels',
        'project_services': 'ProjectServices',
        'projects': 'Projects',
        'runtime_environments': 'RuntimeEnvironments',
        'software_updates': 'SoftwareUpdates',
        'svc_bindings': 'SvcBindings',
        'svc_instances': 'SvcInstances'
    }

    def __init__(self, applications=None, categories=None, cloud_profiles=None, container_registries=None, data_pipelines=None, data_sources=None, functions=None, log_collectors=None, ml_models=None, project_services=None, projects=None, runtime_environments=None, software_updates=None, svc_bindings=None, svc_instances=None):  # noqa: E501
        """EdgeInventoryDeltaPayload - a model defined in Swagger"""  # noqa: E501
        self._applications = None
        self._categories = None
        self._cloud_profiles = None
        self._container_registries = None
        self._data_pipelines = None
        self._data_sources = None
        self._functions = None
        self._log_collectors = None
        self._ml_models = None
        self._project_services = None
        self._projects = None
        self._runtime_environments = None
        self._software_updates = None
        self._svc_bindings = None
        self._svc_instances = None
        self.discriminator = None
        if applications is not None:
            self.applications = applications
        if categories is not None:
            self.categories = categories
        if cloud_profiles is not None:
            self.cloud_profiles = cloud_profiles
        if container_registries is not None:
            self.container_registries = container_registries
        if data_pipelines is not None:
            self.data_pipelines = data_pipelines
        if data_sources is not None:
            self.data_sources = data_sources
        if functions is not None:
            self.functions = functions
        if log_collectors is not None:
            self.log_collectors = log_collectors
        if ml_models is not None:
            self.ml_models = ml_models
        if project_services is not None:
            self.project_services = project_services
        if projects is not None:
            self.projects = projects
        if runtime_environments is not None:
            self.runtime_environments = runtime_environments
        if software_updates is not None:
            self.software_updates = software_updates
        if svc_bindings is not None:
            self.svc_bindings = svc_bindings
        if svc_instances is not None:
            self.svc_instances = svc_instances

    @property
    def applications(self):
        """Gets the applications of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The applications of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._applications

    @applications.setter
    def applications(self, applications):
        """Sets the applications of this EdgeInventoryDeltaPayload.


        :param applications: The applications of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._applications = applications

    @property
    def categories(self):
        """Gets the categories of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The categories of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """Sets the categories of this EdgeInventoryDeltaPayload.


        :param categories: The categories of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._categories = categories

    @property
    def cloud_profiles(self):
        """Gets the cloud_profiles of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The cloud_profiles of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._cloud_profiles

    @cloud_profiles.setter
    def cloud_profiles(self, cloud_profiles):
        """Sets the cloud_profiles of this EdgeInventoryDeltaPayload.


        :param cloud_profiles: The cloud_profiles of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._cloud_profiles = cloud_profiles

    @property
    def container_registries(self):
        """Gets the container_registries of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The container_registries of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._container_registries

    @container_registries.setter
    def container_registries(self, container_registries):
        """Sets the container_registries of this EdgeInventoryDeltaPayload.


        :param container_registries: The container_registries of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._container_registries = container_registries

    @property
    def data_pipelines(self):
        """Gets the data_pipelines of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The data_pipelines of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._data_pipelines

    @data_pipelines.setter
    def data_pipelines(self, data_pipelines):
        """Sets the data_pipelines of this EdgeInventoryDeltaPayload.


        :param data_pipelines: The data_pipelines of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._data_pipelines = data_pipelines

    @property
    def data_sources(self):
        """Gets the data_sources of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The data_sources of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._data_sources

    @data_sources.setter
    def data_sources(self, data_sources):
        """Sets the data_sources of this EdgeInventoryDeltaPayload.


        :param data_sources: The data_sources of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._data_sources = data_sources

    @property
    def functions(self):
        """Gets the functions of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The functions of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._functions

    @functions.setter
    def functions(self, functions):
        """Sets the functions of this EdgeInventoryDeltaPayload.


        :param functions: The functions of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._functions = functions

    @property
    def log_collectors(self):
        """Gets the log_collectors of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The log_collectors of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._log_collectors

    @log_collectors.setter
    def log_collectors(self, log_collectors):
        """Sets the log_collectors of this EdgeInventoryDeltaPayload.


        :param log_collectors: The log_collectors of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._log_collectors = log_collectors

    @property
    def ml_models(self):
        """Gets the ml_models of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The ml_models of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._ml_models

    @ml_models.setter
    def ml_models(self, ml_models):
        """Sets the ml_models of this EdgeInventoryDeltaPayload.


        :param ml_models: The ml_models of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._ml_models = ml_models

    @property
    def project_services(self):
        """Gets the project_services of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The project_services of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._project_services

    @project_services.setter
    def project_services(self, project_services):
        """Sets the project_services of this EdgeInventoryDeltaPayload.


        :param project_services: The project_services of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._project_services = project_services

    @property
    def projects(self):
        """Gets the projects of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The projects of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._projects

    @projects.setter
    def projects(self, projects):
        """Sets the projects of this EdgeInventoryDeltaPayload.


        :param projects: The projects of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._projects = projects

    @property
    def runtime_environments(self):
        """Gets the runtime_environments of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The runtime_environments of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._runtime_environments

    @runtime_environments.setter
    def runtime_environments(self, runtime_environments):
        """Sets the runtime_environments of this EdgeInventoryDeltaPayload.


        :param runtime_environments: The runtime_environments of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._runtime_environments = runtime_environments

    @property
    def software_updates(self):
        """Gets the software_updates of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The software_updates of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._software_updates

    @software_updates.setter
    def software_updates(self, software_updates):
        """Sets the software_updates of this EdgeInventoryDeltaPayload.


        :param software_updates: The software_updates of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._software_updates = software_updates

    @property
    def svc_bindings(self):
        """Gets the svc_bindings of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The svc_bindings of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._svc_bindings

    @svc_bindings.setter
    def svc_bindings(self, svc_bindings):
        """Sets the svc_bindings of this EdgeInventoryDeltaPayload.


        :param svc_bindings: The svc_bindings of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._svc_bindings = svc_bindings

    @property
    def svc_instances(self):
        """Gets the svc_instances of this EdgeInventoryDeltaPayload.  # noqa: E501


        :return: The svc_instances of this EdgeInventoryDeltaPayload.  # noqa: E501
        :rtype: list[EntityVersionMetadata]
        """
        return self._svc_instances

    @svc_instances.setter
    def svc_instances(self, svc_instances):
        """Sets the svc_instances of this EdgeInventoryDeltaPayload.


        :param svc_instances: The svc_instances of this EdgeInventoryDeltaPayload.  # noqa: E501
        :type: list[EntityVersionMetadata]
        """

        self._svc_instances = svc_instances

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EdgeInventoryDeltaPayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EdgeInventoryDeltaPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
