
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-06T11:59:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8668f23c2f0889cd0206a31b5350355942e2659a",
 "version": "0.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
