[tool.poetry]
name = "dvenv"
version = "0.1.4"
description = ""
authors = ["Luke Lombardi <luke@slai.io>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"
PyYAML = "^5.4.1"
redis = "^3.5.3"
asgiref = "^3.4.1"
sdist = "^0.0.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.6b0"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dvenv = 'dvenv:main.main'
dpython = 'dvenv:runner.python'