[tool.poetry]
name = "arductl"
version = "0.0.9"
description = "Helper Library to execute ArduPilot simulations using a Docker Container and dronekit."
authors = ["Aniruddh Chandratre <achand75@asu.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1, <3.10"
dronekit = "^2.9.2"
numpy = "^1.20.3"
pymavlink = "^2.4.15"
MAVProxy = "^1.8.38"
pydantic = "^1.8.2"
docker = "^5.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
