[package]
name = "rustpycoils"
version = "0.1.0"
authors = ["jdrtommey <jake.tommey@gmail.com>"]
edition = "2018"

[lib]
name = "rustpycoils"
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustycoils = {version = "0.1.1",features=["parallel"]}
numpy = "0.14.0"
[dependencies.pyo3]
version = "0.14.1"
features = ["extension-module"]
