[tool.poetry]
name = "aiobungie"
version = "0.2.4"
description = "A small async api wrapper for the bungie api"
authors = ["nxtlo <dhmony-99@hotmail.com>"]
license = "MIT"
keywords = ['async', 'api', 'destiny', 'bungie']
readme = "README.md"
repository = "https://github.com/nxtlo/aiobungie"
packages = [
    {include = "aiobungie"},
    {include = "aiobungie/**/*.py"}
]

[tool.poetry.dependencies]
python = "^3.8"
python-dateutil = "^2.8.1"
aiohttp = "^3.7.4"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.17.1"
aiosqlite = "^0.17.0"
aiofiles = "^0.7.0"
requests-oauthlib = "^1.3.0"
cryptography = "^3.4.7"
aredis = "^1.1.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
