name: Main

on: [push, pull_request]

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install zsh
      - name: Install Python dependencies
        run: |
          python -m pip install tox
      - name: Run checks and tests
        run: |
          tox -e py
      - name: Upload coverage data file
        uses: actions/upload-artifact@v2
        with:
          name: coverage-data
          path: .coverage.*
          retention-days: 1

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download all coverage data files
        uses: actions/download-artifact@v2
        with:
          name: coverage-data
      - name: Install Python dependencies
        run: |
          python -m pip install tox
      - name: Generate coverage reports
        id: coverage_report
        run: |
          tox -e coverage
          echo "::set-output name=filename::coverage-${GITHUB_REPOSITORY##*/}-${GITHUB_SHA:0:10}"
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.coverage_report.outputs.filename }}
          path: htmlcov
