"""
    STACKL

    stackl  # noqa: E501

    The version of the OpenAPI document: 0.3.4.dev0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import stackl_client
from stackl_client.model.infrastructure_target import InfrastructureTarget


class TestInfrastructureTarget(unittest.TestCase):
    """InfrastructureTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfrastructureTarget(self):
        """Test InfrastructureTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InfrastructureTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
