[tool.poetry]
name = "canopy-network"
version = "0.0.37"
description = "A decentralized social network of personal websites"
authors = ["Angelo Gladding <angelo@lahacker.net>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [
    { include = "canopy" }
]

[tool.poetry.urls]
Homepage = "https://angelogladding.com/code/canopy"
Documentation = "https://angelogladding.com/code/canopy/documentation"
Issues = "https://angelogladding.com/code/canopy/issues"
Changes = "https://angelogladding.com/code/canopy/changes"

[tool.poetry.plugins."web.apps"]
canopy = "canopy:app"

[tool.poetry.dependencies]
python = "^3.9"
understory = "^0.0.39"
# understory = {path = "../understory"}

[tool.poetry.dev-dependencies]
ipython = "^7.24.0"
flake8 = "^3.9.2"
flake8-docstrings = "^1.6.0"
pep8-naming = "^0.11.1"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
black = "^21.6b0"
isort = "^5.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
