[tool.black]
line-length = 79
target_version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | \.vscode
)
'''

[tool.coverage.run]
branch = true
source = ["ipmt"]
omit = ["site-packages", ".tox"]

[tool.pytest.ini_options]
addopts = "-s -v --cov --cov-report term --cov-report=html --cov-config pyproject.toml"
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning:distutils"]

[tool.poetry]
name = "ipmt"
version = "2.0b1"
description = "Schema migration tools for PostgreSQL"
authors = ["InPlat <dev@inplat.ru>"]
keywords = ["ipmt"]
readme = "README.rst"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'Natural Language :: Russian',
]
homepage = "https://github.com/inplat/ipmt"
license = "Apache-2.0"


[tool.poetry.scripts]
ipmt = 'ipmt.cli:main'

[tool.poetry.dependencies]
python = "^3.7"
psycopg2 = "^2.9.1"
Jinja2 = "^3.0.1"
PyYAML = "^5.4.1"
Mako = "^1.1.4"
docker = "^5.0.0"
py = "^1.10.0"


[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
mock = "^4.0.2"
flake8 = "^3.6.0"
pytest-cov = "^2.6.0"
Sphinx = "^3.2.1"
watchdog = "^0.10.3"
tox = "^3.20.1"
codecov = "^2.1.10"
coverage = {extras = ["toml"], version = "^5.3"}
toml = "^0.10.1"
black = "^20.8b1"
safety = "^1.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
