
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-07T14:58:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "889ac5da6ca4704396d6a551ef018d55fd51d093",
 "version": "0.7.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
