# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tail_ff.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tail_status(object):
    def setupUi(self, tail_status):
        tail_status.setObjectName("tail_status")
        tail_status.resize(254, 75)
        self.vbox_tail = QtWidgets.QVBoxLayout(tail_status)
        self.vbox_tail.setObjectName("vbox_tail")
        spacerItem = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vbox_tail.addItem(spacerItem)
        self.hbox_kick = QtWidgets.QHBoxLayout()
        self.hbox_kick.setObjectName("hbox_kick")
        self.lab_kick = QtWidgets.QLabel(tail_status)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lab_kick.setFont(font)
        self.lab_kick.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_kick.setObjectName("lab_kick")
        self.hbox_kick.addWidget(self.lab_kick)
        self.lab_kick_value = QtWidgets.QLabel(tail_status)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lab_kick_value.setFont(font)
        self.lab_kick_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_kick_value.setObjectName("lab_kick_value")
        self.hbox_kick.addWidget(self.lab_kick_value)
        self.hbox_kick.setStretch(0, 2)
        self.hbox_kick.setStretch(1, 1)
        self.vbox_tail.addLayout(self.hbox_kick)
        spacerItem1 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vbox_tail.addItem(spacerItem1)
        self.vbox_tail.setStretch(0, 1)
        self.vbox_tail.setStretch(1, 2)
        self.vbox_tail.setStretch(2, 1)

        self.retranslateUi(tail_status)
        QtCore.QMetaObject.connectSlotsByName(tail_status)

    def retranslateUi(self, tail_status):
        _translate = QtCore.QCoreApplication.translate
        tail_status.setWindowTitle(_translate("tail_status", "Form"))
        self.lab_kick.setText(_translate("tail_status", "Kick-Status:"))
        self.lab_kick_value.setText(_translate("tail_status", "No"))
