[tool.poetry]
name = "graia-broadcast"
version = "0.11.3"
description = "a highly customizable, elegantly designed event system based on asyncio"
authors = ["GreyElaina <GreyElaina@outlook.com>"]
license = "MIT"
packages = [
    { include = "graia", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pre-commit = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
