# Generated by Django 3.2.3 on 2021-06-08 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('minified_content', models.TextField(verbose_name='Minified content')),
                ('serve_minified', models.BooleanField(default=True, verbose_name='Serve a minified version of the content')),
                ('filename', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Filename')),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comment')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('serve_minified', models.BooleanField(default=True, verbose_name='Serve a minified version of the content')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comment')),
                ('created_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Created date')),
                ('state', models.CharField(choices=[('current', 'current'), ('previous', 'previous')], editable=False, max_length=8, verbose_name='State')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyncss.file', verbose_name='File')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Version',
            },
        ),
    ]
