dist: focal
language: python
cache: pip
python:
  - 3.7
  - 3.8
  - 3.9
env:
  - WITH_MPI=no
  - WITH_MPI=yes MPI4PY_VERSION=3.0.3 NETCDF4_PYTHON_VERSION=1.5.7
before_install:
  - sudo apt-get update
  - sudo apt-get install libfftw3-dev libopenblas-dev
  - if [ "$WITH_MPI" == "yes" ]; then sudo apt-get install openmpi-bin libopenmpi-dev libfftw3-mpi-dev libhdf5-mpi-dev libpnetcdf-dev libnetcdf-pnetcdf-dev; fi
install:
  - if [ "$WITH_MPI" == "yes" ]; then CC=mpicc python -m pip install -v --force-reinstall --no-binary mpi4py mpi4py==${MPI4PY_VERSION}; fi
  - python -m pip install -r requirements.txt --no-binary setuptools_scm
  - if [ "$WITH_MPI" == "yes" ]; then NETCDF4_DIR=/usr/lib/x86_64-linux-gnu/netcdf/pnetcdf CC=mpicc python -m pip install --force-reinstall -v --no-binary netCDF4 netCDF4==${NETCDF4_PYTHON_VERSION}; fi
  - python .check_netcdf_capabilities.py $WITH_MPI
  - python setup.py sdist
  - python -m pip install dist/*.tar.gz
script:
  - if [ "$WITH_MPI" == "yes" ]; then python run-tests.py --no-build --verbose --full-trace; else python -m pytest --flake8 --verbose --full-trace -s; fi
notifications:
  email:
    - antoine.sanner@imtek.uni-freiburg.de
    - lars.pastewka@imtek.uni-freiburg.de
