
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-12T17:23:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c7218bd049841ce7a48ab78ffa9d334b200d5e68",
 "version": "0.15.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
