name: DB12 testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.9, 2.7]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
  
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: python
        environment-file: environment.yml
        
    - uses: actions/checkout@v2
    - name: Store result in separate file
      run: python src/DIRACbenchmark/dirac_benchmark.py > result_python${{ matrix.python-version }}.txt
    
    - uses: actions/upload-artifact@v2
      with:
        name: Integration test 
        path: result_python${{ matrix.python-version }}.txt
      
