name: Bump Version
on:
  push:
    branches:
      - master
jobs:
  bump-version-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        # Ensure full history is gotten.
        with:
          fetch-depth: 0
#          persist-credentials: false
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
