[tool.poetry]
name = "fitter-python"
version = "0.1.0"
description = "A fitter Python project"
authors = ["Anthony Jatobá <anthonyjatoba@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/anthonyjatoba/fitter-python"
repository = "https://github.com/anthonyjatoba/fitter-python"
keywords = ["fitter python"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.1"
requests = "^2.25.1"
desert = "^2020.11.18"
marshmallow = "^3.12.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
coverage = {extras = ["toml"], version = "^5.5"}
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
black = "^21.6b0"
flake8 = "^3.9.2"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^21.4.3"
flake8-import-order = "^0.18.1"
safety = "^1.10.3"
mypy = "^0.910"
pytype = {version = "^2021.6.17", python = "3.7"}
typeguard = "^2.12.1"
flake8-annotations = "^2.6.2"
flake8-docstrings = "^1.6.0"
darglint = "^1.8.0"
xdoctest = "^0.15.5"
Sphinx = "^4.0.3"
sphinx-autodoc-typehints = "^1.12.0"
codecov = "^2.1.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
fitter-python = "fitter_python.console:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["fitter_python"]

[tool.coverage.report]
show_missing = true
fail_under = 100
