
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-12T16:17:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "89fe2bef9dd51a6eb6df387dd127ed9ffa13e48f",
 "version": "v2.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
