
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-08T10:35:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d94e49aab1b76f79d3b4060cc8ac534ae5b314b",
 "version": "1.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
