[tool.poetry]
name = "noject"
version = "0.1.0"
description = "A pain-free solution for writing in-line SQL safely."
authors = ["tlonny <t@lonny.io>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pylama = "^7.7.1"
pyflakes = "^2.3.1"
black = "^21.6b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
