from setuptools import find_packages, setup


setup(
    name='gavb-nlp',
    packages=find_packages(),
    version='0.0.2',
    description='NLP preprocessing for different nlp tasks.',
    long_description=open('README.txt').read() + '\n\n' + open('CHANGELOG.txt').read(),
    author='Felipe Oliveria / Luiz Simioni / GAVB Deep Learning',
    license='MIT',
    url='https://github.com/felipeoliverai/gavb-nlp',
    install_requires=["blis==0.7.4",
                    "catalogue==2.0.4",
                    "certifi==2021.5.30",
                    "chardet==4.0.0",
                    "click==7.1.2",
                    "colorama==0.4.4",
                    "cymem==2.0.5",
                    "emoji==1.2.0",
                    "filelock==3.0.12",
                    "huggingface-hub==0.0.12",
                    "idna==2.10",
                    "Jinja2==3.0.1",
                    "joblib==1.0.1",
                    "MarkupSafe==2.0.1",
                    "murmurhash==1.0.5",
                    "nltk==3.6.2",
                    "numpy==1.20.3",
                    "packaging==20.9",
                    "pandas==1.2.4",
                    "pathy==0.5.2",
                    "preshed==3.0.5",
                    "py4j==0.10.9",
                    "pydantic==1.7.4",
                    "pyparsing==2.4.7",
                    "python-dateutil==2.8.1",
                    "pytz==2021.1",
                    "PyYAML==5.4.1",
                    "regex==2021.4.4",
                    "requests==2.25.1",
                    "sacremoses==0.0.45",
                    "six==1.16.0",
                    "smart-open==3.0.0",
                    "spacy==3.0.6",
                    "spacy-legacy==3.0.6",
                    "srsly==2.4.1",
                    "thinc==8.0.6",
                    "tokenizers==0.10.3",
                    "torch==1.9.0",
                    "tqdm==4.60.0",
                    "transformers==4.8.1",
                    "typer==0.3.2",
                    "typing-extensions==3.10.0.0",
                    "urllib3==1.26.5",
                    "wasabi==0.8.2"]
)
