#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['faust_large_message_serializer',
 'faust_large_message_serializer.blob_storage',
 'faust_large_message_serializer.clients',
 'faust_large_message_serializer.utils']

package_data = \
{'': ['*']}

install_requires = \
['boto3',
 'faust-streaming',
 'bump2version',
 'types-boto',
 'azure-storage-blob',
 'loguru']

extras_require = \
{":python_version == '3.6'": ['dataclasses'],
 'test': ['pytest', 'pytest-cov', 'botocore', 'pytest-docker-compose']}

setup(name='faust-large-message-serializer',
      version='2.0.0',
      description='Faust serializer that serializes large messages on Amazon S3 or Azure Blob Storage',
      author='bakdata',
      author_email='opensource@bakdata.com',
      url='https://github.com/bakdata/faust-s3-backed-serializer',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
