[tool.poetry]
name = "understory-web"
version = "0.0.21"
description = "Tools for metamodern web development"
authors = ["Angelo Gladding <angelo@lahacker.net>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [
    { include = "understory" }
]

[tool.poetry.urls]
Homepage = "https://github.com/canopy/understory-web"

[tool.poetry.scripts]
web = "understory.web.__main__:main"

[tool.pyright]
reportGeneralTypeIssues = "none"

[tool.poetry.dependencies]
python = "^3.7"
gunicorn = "^20.1.0"
hstspreload = "^2020.12.22"
pendulum = "^2.1.2"
requests = "^2.25.1"
mf2py = "^1.1.2"
mf2util = "^0.5.1"
lxml = "^4.6.3"
understory-code = "^0.0.44"
understory-fx = "^0.0.5"
understory-db = "^0.0.8"
understory-term = "^0.0.6"
networkx = "^2.5.1"
pyscreenshot = "^3.0"
Pillow = "^8.2.0"
PyVirtualDisplay = "^2.1"
selenium = "^3.141.0"
gevent = "^21.1.2"
jsonpatch = "^1.32"
pycryptodome = "^3.10.1"
Unidecode = "^1.2.0"
watchdog = "^2.1.2"
httpagentparser = "^1.9.1"
mimeparse = "^0.1.3"
acme-tiny = "^4.1.0"
scrypt = "^0.8.18"
vobject = "^0.9.6"
cssselect = "^1.1.0"
dnspython = "^2.1.0"
feedparser = "^6.0.2"
regex = "^2021.4.4"

[tool.poetry.dev-dependencies]
ipython = "^7.23.1"
flake8 = "^3.9.2"
flake8-docstrings = "^1.6.0"
pep8-naming = "^0.11.1"
pytest = "^6.2.4"
pytest-cov = "^2.12.0"
pyre-check = "^0.9.3"
black = "^21.5b2"
pynvim = "^0.4.3"
pytest-gevent = "^1.1.0"
webdriver-manager = "^3.4.2"
isort = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
