[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "requests==2.25.1",
    "bs4==0.0.1",
    "opencv-python==3.1.0",
    "numpy==1.16.6",
    "urllib3==1.24.3"
]
build-backend = "setuptools.build_meta"