[tool.poetry]
name = "ewah_bool_utils"
version = "0.1.0"
description = "EWAH Bool Array utils for yt"
authors = ["Matthew Turk", "Meagan Lang", "Navaneeth Suresh"]
license = "BSD License"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "oldest-supported-numpy"
Cython = ">= 0.29.21, < 3.0"
flake8 = "^3.9.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = [
  "setuptools >= 19.6",
  "wheel >= 0.36.2",
  "Cython >= 0.29.21, < 3.0",
  "oldest-supported-numpy",
  "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"
