[build-system]
requires = [ "setuptools>=42", "wheel" ]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py3{6,7,8,9}

[testenv]
platform = linux
deps = -rrequirements.txt
commands = python tests/test_configize.py -v"""
