# coding: utf-8

"""
    Karbon Platform Services API reference.

    OpenAPI documentation for public facing Karbon Platform Services API  This API documentation is generated from source code using go-swagger. Do not edit the generated kps_api.json directly!  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: karbon-platform-services-api@nutanix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kps_api
from models.service_domain import ServiceDomain  # noqa: E501
from kps_api.rest import ApiException


class TestServiceDomain(unittest.TestCase):
    """ServiceDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceDomain(self):
        """Test ServiceDomain"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kps_api.models.service_domain.ServiceDomain()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
