# Generated by Django 3.2 on 2021-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebox_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]

