[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "myst-alpha"
version = "0.0.1"
description = "This is the official Python library for the Myst Platform."
license = "Apache-2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: PyPy",
]
authors = ["Myst AI, Inc. <support@myst.ai>"]
readme = "README.md"
include = ["LICENSE", "CHANGELOG.md", "myst/openapi_client"]
packages = [
    { include = "myst" },
]

[tool.poetry.dependencies]
python = "^3.6.2"
google-auth = "<2.0.0,>=1.11.0"
google-auth-oauthlib = "<1.0.0,>=0.4.1"
pytz = ">=2019.1"
urllib3 = "<2.0.0,>=1.24.3"
toml = "^0.10.2"
httpx = ">=0.15.4,<0.19.0"
attrs = ">=20.1.0,<22.0.0"
python-dateutil = "^2.8.0"

[tool.poetry.dev-dependencies]
check-manifest = ">=0.37"
coverage = ">=5.5"
readme-renderer = "==24.0"
responses = "<1.0.0,>=0.10.6"
twine = ">=1.13.0"
black = "^21.6b0"
mypy = "^0.910"
openapi-python-client = "^0.9.2"
plumbum = "^1.7.0"
typer = "^0.3.2"
types-pytz = "^2021.1.0"
types-toml = "^0.1.3"
types-dataclasses = "^0.1.5"
types-setuptools = "^57.0.0"
pytest = "^6.2.4"
pytest-describe = "^1.0.0"
pytest-httpx = "^0.12.0"
isort = "^5.9.1"

[tool.black]
# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | .direnv
)/
'''

[tool.isort]
profile = "black"
skip_glob = ["myst/openapi_client/*"]

[tool.check-manifest]
ignore = [".coveragerc", ".pre-commit-config.yaml", "bitbucket-pipelines.yml", "docs", "docs/*", "__pycache__", "*.pyc"]
