# coding: utf-8

"""
    Karbon Platform Services API reference.

    OpenAPI documentation for public facing Karbon Platform Services API  This API documentation is generated from source code using go-swagger. Do not edit the generated kps_api.json directly!  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: karbon-platform-services-api@nutanix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DataIfcEndpoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'value': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'value': 'value'
    }

    def __init__(self, id=None, name=None, value=None):  # noqa: E501
        """DataIfcEndpoint - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._value = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.value = value

    @property
    def id(self):
        """Gets the id of this DataIfcEndpoint.  # noqa: E501

        ID is the UUID of the data Src/Ifc  # noqa: E501

        :return: The id of this DataIfcEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DataIfcEndpoint.

        ID is the UUID of the data Src/Ifc  # noqa: E501

        :param id: The id of this DataIfcEndpoint.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this DataIfcEndpoint.  # noqa: E501

        Name is the name of the field within the data Src/Ifc. This defines invariant between data ifc and application. If an application is associated w/ a given data ifc field name, that field name cannot be removed from the data ifc until application is no longer the consumer of the field.  # noqa: E501

        :return: The name of this DataIfcEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DataIfcEndpoint.

        Name is the name of the field within the data Src/Ifc. This defines invariant between data ifc and application. If an application is associated w/ a given data ifc field name, that field name cannot be removed from the data ifc until application is no longer the consumer of the field.  # noqa: E501

        :param name: The name of this DataIfcEndpoint.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value(self):
        """Gets the value of this DataIfcEndpoint.  # noqa: E501

        Value is the name of the endpoint within the data Src/Ifc. This could be a topic name or bucket name, etc. Artifacts of a data Ifc be affected by this.  # noqa: E501

        :return: The value of this DataIfcEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DataIfcEndpoint.

        Value is the name of the endpoint within the data Src/Ifc. This could be a topic name or bucket name, etc. Artifacts of a data Ifc be affected by this.  # noqa: E501

        :param value: The value of this DataIfcEndpoint.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataIfcEndpoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataIfcEndpoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
