[tool.poetry]
name = "robyn"
version = "0.5.1"
description = ""
authors = ["Sanskar Jethi <sansyrox@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
