
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-12T11:10:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a73838ece2d08239df096b60ac6458348c5112fe",
 "version": "0.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
