name: build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs: 
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.6, 3.7, 3.8, 3.9]
      env:
          USING_COVERAGE: "3.9"

      steps:
          - name: Checkout sources
            uses: actions/checkout@v2

          - name: Set up Python v ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
                python-version: ${{ matrix.python-version }}

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                python -m pip install black coverage flake8 flit mccabe mypy pylint pytest tox tox-gh-actions pytest-cov

          - name: Run tox
            run: |
                python -m tox

          - name: Generate Report
            run: |
              coverage run -m src.mainentry.mainentry

          - name: "Upload coverage to Codecov"
            uses: codecov/codecov-action@v1
            if: contains(env.USING_COVERAGE, matrix.python-version)
            with:
              token: ${{ secrets.CODECOV_TOKEN }} 
              fail_ci_if_error: true


