[package]
name = "rjsonnet"
version = "0.4.2"
authors = ["messense <messense@icloud.com>"]
edition = "2018"
description = "Python bindings to Rust jrsonnet crate"
license = "MIT"
repository = "https://github.com/messense/rjsonnet-py"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rjsonnet"
crate-type = ["cdylib"]

[dependencies]
jrsonnet-evaluator = "0.4.1"
jrsonnet-gc = "0.4.2"
jrsonnet-parser = "0.4.1"
pyo3 = { version = "0.14.1", features = ["abi3-py36", "extension-module"] }
