[tool.poetry]
name = "mmidata"
version = "0.1.1"
description = ""
authors = ["Dan Sikes <dan@methodmi.com>"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.3.2"
boto3 = "^1.17.107"
humanize = "^3.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mmidata = 'mmidata.main:cli'
