
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-09T16:31:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "24a61eb480609c0b6fc48dc47edd60f8342bb05e",
 "version": "4.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
